# Dependencies
markdown:	redcarpet
highlighter:	pygments

# Permalinks
permalink:	/blog/:title

# Setup
title:		Thoughts of Sorts
tagline:	'blog'
description:	"A programming blog."
url:		https://gabrieltalyor.github.io

author:
  name:		'Gabriel Taylor-Russ'
  url:		https://gabrieltaylor.github.io

paginate:	5

# Custom vars
icon:		/assets/images/icon.png
cover:		/assets/images/cover.jpg

social:
  - icon:	twitter
    url:	https://twitter.com/gabrielruss
    desc:	Follow me on twitter

  - icon:	github
    url:	https://github.com/gabrieltaylor
    desc:	Fork me on github

  - icon:	googleplus-alt
    url:	https://google.com/+GabrielTaylorRuss
    desc:	Add me on google+

    
menu:
  - title:	Home
    url:	/
    
  - title:	About
    url:	/about
    
copyright:
  author:	Gabriel Taylor-Russ
  url:		https://gabrieltaylor.github.io
  type_title:	Some rights reserved
  type_url:	http://creativecommons.org/licenses/by-nc/2.5
