# Dependencies
markdown:	redcarpet
highlighter:	pygments

# Permalinks
permalink:	/blog/:title

# Setup
title:		Thoughts of Sorts
tagline:	'blog'
description:	"A programming blog."
url:		https://gabrieltaylor.github.io

author:
  name:		'Gabriel Taylor-Russ'
  url:		https://gabrieltaylor.github.io

paginate:	5

# Custom vars
icon:		/assets/images/icon.png
cover:		/assets/images/cover.jpg

social:
  - icon:	github
    url:	https://github.com/gabrieltaylor
    desc:	See my repos on Github

  - icon: linkedin
    url:  https://ca.linkedin.com/in/gabrieltaylorruss
    desc: Connect with me on LinkedIn

  - icon:	googleplus-alt
    url:	https://google.com/+GabrielTaylorRuss
    desc:	Add me on Google+


menu:
  - title:	Home
    url:	/

  - title:	About
    url:	/about

copyright:
  author:	Gabriel Taylor-Russ
  url:		https://gabrieltaylor.github.io
  type_title:	Some rights reserved
  type_url:	http://creativecommons.org/licenses/by-nc/2.5
